// Datos mock para desarrollo — Fase 1
// Estos datos se reemplazarán por consultas a Supabase en la Fase 2.
// Los precios están en CÉNTIMOS (12.500€ = 1250000)

import { Vehiculo } from "@/types/vehiculo";

export const vehiculosMock: Vehiculo[] = [
  {
    id: "1",
    marca: "BMW",
    modelo: "Serie 3",
    version: "320d M Sport",
    slug: "bmw-serie-3-2021",
    anio: 2021,
    kilometraje: 45000,
    precio: 2890000,
    precio_anterior: 3150000,
    combustible: "diesel",
    cambio: "automatico",
    carroceria: "sedan",
    potencia: 190,
    color: "Negro Zafiro",
    plazas: 5,
    puertas: 4,
    garantia: "Garantía de 12 meses incluida",
    descripcion: "BMW Serie 3 en estado impecable. Interior en cuero Dakota, navegación profesional, faros LED adaptativos, asientos calefactados. Mantenimiento oficial al día.",
    estado: "disponible",
    destacado: true,
    visitas: 234,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-15T08:00:00Z",
    imagenes: [
      { id: "img1", vehicle_id: "1", url: "/mock/bmw-320d-1.png", orden: 0, es_principal: true, created_at: "2024-03-01T10:00:00Z" },
      { id: "img2", vehicle_id: "1", url: "/mock/bmw-320d-2.png", orden: 1, es_principal: false, created_at: "2024-03-01T10:00:00Z" },
    ],
  },
  {
    id: "2",
    marca: "Mercedes-Benz",
    modelo: "Clase A",
    version: "A 200 AMG Line",
    slug: "mercedes-benz-clase-a-2022",
    anio: 2022,
    kilometraje: 28000,
    precio: 3250000,
    combustible: "gasolina",
    cambio: "automatico",
    carroceria: "sedan",
    potencia: 163,
    color: "Gris Montaña",
    plazas: 5,
    puertas: 4,
    garantia: "Garantía de 12 meses incluida",
    descripcion: "Mercedes Clase A con acabado AMG Line. Sistema MBUX, pantalla multimedia de 10.25\", cámara trasera, sensores de aparcamiento. Un coche premium a precio de ocasión.",
    estado: "disponible",
    destacado: true,
    visitas: 189,
    created_at: "2024-03-05T10:00:00Z",
    updated_at: "2024-03-10T08:00:00Z",
    imagenes: [
      { id: "img3", vehicle_id: "2", url: "/mock/mercedes-a200-1.png", orden: 0, es_principal: true, created_at: "2024-03-05T10:00:00Z" },
    ],
  },
  {
    id: "3",
    marca: "Audi",
    modelo: "A4",
    version: "35 TFSI S Line",
    slug: "audi-a4-2020",
    anio: 2020,
    kilometraje: 67000,
    precio: 2450000,
    combustible: "gasolina",
    cambio: "automatico",
    carroceria: "sedan",
    potencia: 150,
    color: "Blanco Ibis",
    plazas: 5,
    puertas: 4,
    garantia: "Garantía de 6 meses incluida",
    descripcion: "Audi A4 con pack S Line exterior e interior. Virtual cockpit, navegación MMI, faros LED matrix. Historial completo de mantenimiento.",
    estado: "disponible",
    destacado: true,
    visitas: 156,
    created_at: "2024-02-20T10:00:00Z",
    updated_at: "2024-03-01T08:00:00Z",
    imagenes: [
      { id: "img4", vehicle_id: "3", url: "/mock/audi-a4-1.png", orden: 0, es_principal: true, created_at: "2024-02-20T10:00:00Z" },
    ],
  },
  {
    id: "4",
    marca: "Volkswagen",
    modelo: "Golf",
    version: "1.5 TSI R-Line",
    slug: "volkswagen-golf-2021",
    anio: 2021,
    kilometraje: 38000,
    precio: 2190000,
    combustible: "gasolina",
    cambio: "manual",
    carroceria: "sedan",
    potencia: 150,
    color: "Gris Urano",
    plazas: 5,
    puertas: 5,
    garantia: "Garantía de 12 meses incluida",
    descripcion: "Golf 8 con acabado R-Line. Digital cockpit pro, Discover Media, asistente de aparcamiento. El Golf más tecnológico de la historia.",
    estado: "disponible",
    destacado: false,
    visitas: 142,
    created_at: "2024-02-15T10:00:00Z",
    updated_at: "2024-02-20T08:00:00Z",
    imagenes: [
      { id: "img5", vehicle_id: "4", url: "/mock/vw-golf-1.png", orden: 0, es_principal: true, created_at: "2024-02-15T10:00:00Z" },
    ],
  },
  {
    id: "5",
    marca: "SEAT",
    modelo: "León",
    version: "1.5 TSI FR",
    slug: "seat-leon-2022",
    anio: 2022,
    kilometraje: 22000,
    precio: 1990000,
    combustible: "gasolina",
    cambio: "manual",
    carroceria: "sedan",
    potencia: 150,
    color: "Rojo Deseo",
    plazas: 5,
    puertas: 5,
    garantia: "Garantía de 12 meses incluida",
    descripcion: "SEAT León FR con motor 1.5 TSI EVO. Cuadro digital, navegación, asistentes de conducción de última generación. Deportividad y tecnología.",
    estado: "disponible",
    destacado: false,
    visitas: 98,
    created_at: "2024-03-10T10:00:00Z",
    updated_at: "2024-03-12T08:00:00Z",
    imagenes: [
      { id: "img6", vehicle_id: "5", url: "/mock/seat-leon-1.png", orden: 0, es_principal: true, created_at: "2024-03-10T10:00:00Z" },
    ],
  },
  {
    id: "6",
    marca: "Toyota",
    modelo: "RAV4",
    version: "2.5 Hybrid Advance",
    slug: "toyota-rav4-2023",
    anio: 2023,
    kilometraje: 15000,
    precio: 3590000,
    combustible: "hibrido",
    cambio: "automatico",
    carroceria: "suv",
    potencia: 218,
    color: "Gris Eclipse",
    plazas: 5,
    puertas: 5,
    garantia: "Garantía de fábrica vigente",
    descripcion: "Toyota RAV4 Hybrid con solo 15.000 km. Sistema híbrido auto-recargable, tracción delantera, cámara 360°, Toyota Safety Sense 2.0. Consumo mixto de 5.6L/100km.",
    estado: "disponible",
    destacado: true,
    visitas: 312,
    created_at: "2024-03-12T10:00:00Z",
    updated_at: "2024-03-14T08:00:00Z",
    imagenes: [
      { id: "img7", vehicle_id: "6", url: "/mock/toyota-rav4-1.png", orden: 0, es_principal: true, created_at: "2024-03-12T10:00:00Z" },
    ],
  },
  {
    id: "7",
    marca: "Ford",
    modelo: "Focus",
    version: "1.0 EcoBoost ST-Line",
    slug: "ford-focus-2020",
    anio: 2020,
    kilometraje: 72000,
    precio: 1590000,
    combustible: "gasolina",
    cambio: "manual",
    carroceria: "sedan",
    potencia: 125,
    color: "Azul Performance",
    plazas: 5,
    puertas: 5,
    danios: "Pequeño roce en paragolpes trasero (ver fotos)",
    garantia: "Garantía de 6 meses incluida",
    descripcion: "Ford Focus con el eficiente motor EcoBoost. Acabado ST-Line con suspensión deportiva, asientos deportivos y volante de cuero. Ideal para quien busca diversión al volante.",
    estado: "disponible",
    destacado: false,
    visitas: 87,
    created_at: "2024-02-28T10:00:00Z",
    updated_at: "2024-03-05T08:00:00Z",
    imagenes: [
      { id: "img8", vehicle_id: "7", url: "/mock/ford-focus-1.png", orden: 0, es_principal: true, created_at: "2024-02-28T10:00:00Z" },
    ],
  },
  {
    id: "8",
    marca: "Hyundai",
    modelo: "Tucson",
    version: "1.6 CRDi Tecno",
    slug: "hyundai-tucson-2022",
    anio: 2022,
    kilometraje: 35000,
    precio: 2690000,
    precio_anterior: 2850000,
    combustible: "diesel",
    cambio: "automatico",
    carroceria: "suv",
    potencia: 136,
    color: "Negro Phantom",
    plazas: 5,
    puertas: 5,
    garantia: "Garantía de 12 meses incluida",
    descripcion: "Hyundai Tucson con diseño espectacular. Pantalla de 10.25\", cuadro digital, climatizador bizona, cargador inalámbrico. El SUV más deseado.",
    estado: "reservado",
    destacado: false,
    visitas: 178,
    created_at: "2024-03-08T10:00:00Z",
    updated_at: "2024-03-14T08:00:00Z",
    imagenes: [
      { id: "img9", vehicle_id: "8", url: "/mock/hyundai-tucson-1.png", orden: 0, es_principal: true, created_at: "2024-03-08T10:00:00Z" },
    ],
  },
  {
    id: "9",
    marca: "Peugeot",
    modelo: "3008",
    version: "1.5 BlueHDi Allure",
    slug: "peugeot-3008-2021",
    anio: 2021,
    kilometraje: 52000,
    precio: 2390000,
    combustible: "diesel",
    cambio: "automatico",
    carroceria: "suv",
    potencia: 130,
    color: "Gris Artense",
    plazas: 5,
    puertas: 5,
    garantia: "Garantía de 12 meses incluida",
    descripcion: "Peugeot 3008 con el innovador i-Cockpit. Pantalla táctil de 10\", navegación 3D, grip control, cámara de visión trasera. Diseño que no pasa desapercibido.",
    estado: "disponible",
    destacado: false,
    visitas: 134,
    created_at: "2024-02-25T10:00:00Z",
    updated_at: "2024-03-10T08:00:00Z",
    imagenes: [
      { id: "img10", vehicle_id: "9", url: "/mock/peugeot-3008-1.png", orden: 0, es_principal: true, created_at: "2024-02-25T10:00:00Z" },
    ],
  },
  {
    id: "10",
    marca: "Renault",
    modelo: "Mégane",
    version: "E-Tech 100% Eléctrico",
    slug: "renault-megane-2023",
    anio: 2023,
    kilometraje: 8000,
    precio: 2990000,
    combustible: "electrico",
    cambio: "automatico",
    carroceria: "suv",
    potencia: 220,
    color: "Negro Étoilé",
    plazas: 5,
    puertas: 5,
    garantia: "Garantía de fábrica vigente hasta 2028",
    descripcion: "Renault Mégane E-Tech 100% eléctrico. Autonomía de 450 km WLTP, carga rápida, pantalla OpenR Link de 12\", conducción autónoma nivel 2. El futuro ya está aquí.",
    estado: "disponible",
    destacado: true,
    visitas: 267,
    created_at: "2024-03-14T10:00:00Z",
    updated_at: "2024-03-15T08:00:00Z",
    imagenes: [
      { id: "img11", vehicle_id: "10", url: "/mock/renault-megane-1.png", orden: 0, es_principal: true, created_at: "2024-03-14T10:00:00Z" },
    ],
  },
  {
    id: "11",
    marca: "Kia",
    modelo: "Sportage",
    version: "1.6 T-GDI GT-Line",
    slug: "kia-sportage-2023",
    anio: 2023,
    kilometraje: 12000,
    precio: 3190000,
    combustible: "gasolina",
    cambio: "automatico",
    carroceria: "suv",
    potencia: 150,
    color: "Verde Gravity",
    plazas: 5,
    puertas: 5,
    garantia: "Garantía de fábrica vigente hasta 2030",
    descripcion: "Kia Sportage con la garantía de 7 años. Pantalla doble panorámica de 12.3\", asistentes de conducción, head-up display. El SUV que lo tiene todo.",
    estado: "disponible",
    destacado: false,
    visitas: 203,
    created_at: "2024-03-13T10:00:00Z",
    updated_at: "2024-03-15T08:00:00Z",
    imagenes: [
      { id: "img12", vehicle_id: "11", url: "/mock/kia-sportage-1.png", orden: 0, es_principal: true, created_at: "2024-03-13T10:00:00Z" },
    ],
  },
  {
    id: "12",
    marca: "Dacia",
    modelo: "Duster",
    version: "1.5 dCi Comfort",
    slug: "dacia-duster-2022",
    anio: 2022,
    kilometraje: 41000,
    precio: 1490000,
    combustible: "diesel",
    cambio: "manual",
    carroceria: "suv",
    potencia: 115,
    color: "Marrón Visonío",
    plazas: 5,
    puertas: 5,
    garantia: "Garantía de 12 meses incluida",
    descripcion: "Dacia Duster, el SUV con mejor relación calidad-precio del mercado. MediaNav, cámara trasera, climatización automática. Todo lo que necesitas, sin pagar de más.",
    estado: "disponible",
    destacado: false,
    visitas: 145,
    created_at: "2024-03-02T10:00:00Z",
    updated_at: "2024-03-08T08:00:00Z",
    imagenes: [
      { id: "img13", vehicle_id: "12", url: "/mock/dacia-duster-1.png", orden: 0, es_principal: true, created_at: "2024-03-02T10:00:00Z" },
    ],
  },
];
